// Mock data for development/testing when backend is not available

export const MOCK_CHARACTERS = [
  {
    id: '1',
    name: 'Aria the Adventurer',
    creator: 'SkizoAI Team',
    description: 'A brave adventurer seeking treasures and excitement',
    thumbnail: 'https://via.placeholder.com/300x400/6366f1/ffffff?text=Aria',
    tags: ['Adventure', 'Fantasy', 'SFW'],
    category: 'Fantasy',
    downloads: 1234,
    rating: 4.8,
    ratingCount: 89,
    featured: true,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Luna the Mage',
    creator: 'MagicMaker',
    description: 'A powerful mage with mysterious powers',
    thumbnail: 'https://via.placeholder.com/300x400/8b5cf6/ffffff?text=Luna',
    tags: ['Magic', 'Fantasy', 'SFW'],
    category: 'Fantasy',
    downloads: 2156,
    rating: 4.9,
    ratingCount: 145,
    featured: true,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: '3',
    name: 'Kai the Warrior',
    creator: 'BattleMaster',
    description: 'A skilled warrior with unmatched combat abilities',
    thumbnail: 'https://via.placeholder.com/300x400/ef4444/ffffff?text=Kai',
    tags: ['Action', 'Fantasy', 'SFW'],
    category: 'Fantasy',
    downloads: 987,
    rating: 4.6,
    ratingCount: 67,
    featured: false,
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '4',
    name: 'Sakura the Idol',
    creator: 'IdolProducer',
    description: 'A cheerful idol who loves performing',
    thumbnail: 'https://via.placeholder.com/300x400/ec4899/ffffff?text=Sakura',
    tags: ['Idol', 'Anime', 'SFW'],
    category: 'Anime',
    downloads: 3421,
    rating: 4.7,
    ratingCount: 234,
    featured: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: '5',
    name: 'Zero the Hacker',
    creator: 'CyberPunk',
    description: 'A skilled hacker navigating the digital world',
    thumbnail: 'https://via.placeholder.com/300x400/10b981/ffffff?text=Zero',
    tags: ['Cyberpunk', 'Sci-Fi', 'SFW'],
    category: 'Sci-Fi',
    downloads: 1567,
    rating: 4.5,
    ratingCount: 98,
    featured: false,
    createdAt: '2024-01-12T00:00:00Z',
    updatedAt: '2024-01-12T00:00:00Z',
  },
  {
    id: '6',
    name: 'Miko the Shrine Maiden',
    creator: 'ShrineKeeper',
    description: 'A gentle shrine maiden with spiritual powers',
    thumbnail: 'https://via.placeholder.com/300x400/f59e0b/ffffff?text=Miko',
    tags: ['Spiritual', 'Anime', 'SFW'],
    category: 'Anime',
    downloads: 2890,
    rating: 4.9,
    ratingCount: 187,
    featured: true,
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-08T00:00:00Z',
  },
  {
    id: '7',
    name: 'Rex the Space Captain',
    creator: 'SpaceExplorer',
    description: 'A fearless captain exploring the cosmos',
    thumbnail: 'https://via.placeholder.com/300x400/3b82f6/ffffff?text=Rex',
    tags: ['Space', 'Sci-Fi', 'SFW'],
    category: 'Sci-Fi',
    downloads: 1123,
    rating: 4.4,
    ratingCount: 76,
    featured: false,
    createdAt: '2024-01-18T00:00:00Z',
    updatedAt: '2024-01-18T00:00:00Z',
  },
  {
    id: '8',
    name: 'Yuki the Ninja',
    creator: 'ShadowMaster',
    description: 'A stealthy ninja with incredible agility',
    thumbnail: 'https://via.placeholder.com/300x400/6366f1/ffffff?text=Yuki',
    tags: ['Ninja', 'Action', 'SFW'],
    category: 'Action',
    downloads: 2345,
    rating: 4.8,
    ratingCount: 156,
    featured: true,
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
  },
];

export const MOCK_CATEGORIES = ['Fantasy', 'Anime', 'Sci-Fi', 'Action', 'Romance', 'Horror'];

export const MOCK_TAGS = [
  'SFW',
  'NSFW',
  'Adventure',
  'Magic',
  'Cyberpunk',
  'Space',
  'Ninja',
  'Idol',
  'Spiritual',
  'Action',
];

export const MOCK_CHARACTER_DATA = {
  name: 'Sample Character',
  bio_character: 'This is a sample character for testing.',
  personality: 'Friendly and helpful',
  scenario: 'A casual conversation',
  initial_message: 'Hello! Nice to meet you!',
  message_example: '<START>\nUser: Hi!\nCharacter: Hello there!',
  character_image_base64: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
};
